### ISSUE TITLE
Feature-set evaluation

### ISSUE THREAD

**Issue by zerok** [django-backup/django-backup#20]
Right now we have tons of features in here that kind of look outdated and are probably used by only one person if even that. Automated rsync and esp. FTP is high on the list of features I'd love to remove as they just blow this app up for minimal benefit that couldn't be solved with one line a wrapping shell-script (which is probably there anyway).

Right now this app simply does _too much_ which makes it really hard to iterate on new releases. Perhaps we could do a little cleanup with 3.x?

**Comment by andybak** [comment]
I had a debate on this issue with the maintainer of a separate project - I initiated a discussion about a potential code merge but he wanted his project to restrict itself solely to db backups.

For me the key role for django-backup is to solve the backup issues for a typical website and provide a sensible opinionated workflow for backups.

In my view the ideal workflow for media backups is differential rsync backups. Zipping and FTPing the media directory is slower and uses more disk space.

Another key feature is managing the number of copies of db and media that are retained. Moving this functionality into a separate app is feasible but I don't see much gain here.

Restoring backups is inherently useful (how do you test your backups unless you can easily restore?) and shares enough logic and settings with the backup itself that moving this into a separate app makes little sense to me.

Bearing this in mind - what features would you suggest removing?

**Comment by zerok** [comment]
I mostly agree, just not that transferring should be part of core feature-set :) Anything that is related to transferring the backups to and from a location other than a simple folder on the same folder is simply to setup-specific for me. 

We should make the core workflow as simple as possible: Backing up and restoring a complete database + media folder to and from a common archive format within a folder. Where these files are archived should be up to the user. 

If the files in the local folder are date-rotated, I don't really mind. I just don't see doing that on a remote location as part of the core feature-set. So I'd remove following features:
- Anything that does anything on a remote server
- Anything that is FTP related
- Anything that is rsync related

With that we would get rid of ~90% of the configuration flags and make the whole process much easier for users. I can only speak for myself, obviously, but a typical user is probably already running django-backup as part of a cronjob, which is most likely already wrapped in a shell script. Including dozens of flags instead of just using the output filename in subsequent calls isn't "obvious" to me :)

**Comment by andybak** [comment]
I agree that the configuration parameters are confusing and would like to review those. (Maybe all the config can be moved into a settings dict and the only param to the management command is to choose a config?)

With regards to the scope of django-backup. I feel there's already apps that solve various parts of the process. However that leaves a lot of stuff for the users of those apps to think about - rather than just solving the problem for them. I would assume that backups are orthogonal to the task they are trying to solve - so why not take that job away from them 

I want an app that solves my problem in it's entirety - "back up my Django website". If the files are left on the local drive then that leaves me a job to worry abou. For me the appeal of django-backup is that it's simple (at least in theory - that part needs some work) and it's complete. I'm happy if it's opinionated as I think there's already smaller, more focussed and less opinionated apps out there.

A user should be able to install django-backup, fill in some settings and come away with a reasonably sane and complete backup workflow. They shouldn't have to write any code to achieve this. 

To me - it's similar to the difference between the Django philosophy and the Flask/Pyramid philosophy. I can see the arguments for both but I chose Django because it solves the 90% of the common case without me needing to glue together several separate apps.

**Comment by andybak** [comment]
I'm about to partially contradict myself. ;-)

The one flaw with Django Backup currently is that the site pushes backups to the backup server. This means that if the site is ever compromised - then the backup server potentially also is. 

Ideally, we'd have a backup server that pulled backups from the site - therefore the site itself wouldn't have access to the backup server and we'd lose another single point of failure.

However - this is a major design change and would require writing and deploying more code on the backup server. (it could however be fairly simple. It doesn't need to have a persistent service running other than a cron daemon). In this scenario - django backup would be reduced to the role of creating a db dump. Handling rsync/media files would be run from the backup server itself - as would scheduling and backup retention.

I need to give this a bit more thought but it would be a much more secure approach.

**Comment by zerok** [comment]
:-) This is pretty much what I'm doing for some sites. Another alternative is to encrypt the backup on-site and then push it to something like S3 with a user that only has permissions to create new objects but not manipulate any of them.

These are the main reasons why I don't use the transfer features in django-backup right now ;-)

**Comment by andybak** [comment]
S3 is obviously tempting but I'd hate to lose differential backups. Maybe I need to do some maths and compare the cost of non-diff backups vs diffed. 

The main need for this came from some sites that have very large media directories where most of it changes very infrequently. Differential backups are ideal for this - both in reducing time and space for each backup.

**Comment by zerok** [comment]
That absolutely sounds like a valid use-case! Alternatively, would it make sense to provide an option that the media files are simply not packaged by default but just copied to a backup folder where they could then be rsync'd?

**Comment by andybak** [comment]
I don't see how that helps. The rsyncing task still needs to run, still needs logic around retention, still needs to share settings.

I'd like to keep the goal of the project as "install this, add a few settings and you'll have a sane and complete backup regime". The more we move away from that goal, the less useful the project would be to me personally.

**Comment by zerok** [comment]
OK :) I think that's enough feature-eval for now. We have a goal, now we just have to find a clean way to get there. Once there is a 2.0 perhaps we can look through some of the configs to make the whole system easier to configure and in the background more cleanly organized :)
